spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sweets-factory
    username: marcin
    password: marcin
    driverClassName: org.postgresql.Driver

rabbitmq:
  queue:
    name: my-queue

neo4j:
  server:
    username: neo4j-user
    password: password

logging:
  path: logs

debug: true